public with sharing class Diff1Class {
    /*public Diff1Class() {

    }*/

    public static void messageClassDebug(){
        System.debug('Thhis is the first debug class');
    }

    public static void messageClassDebug1(){
        System.debug('Thhis is the first debug class1111');
    }

    public static void messageClassDebug2(){
        System.debug('Thhis is the first debug class2222');
    }

    public static void messageClassDebug3(){
        System.debug('Thhis is the first debug class3333');
    }

    public static void messageClassDebug4(){
        System.debug('Thhis is the first debug class4444');
    }

    public static void messageClassDebug5(){
        System.debug('Thhis is the first debug class5555');
    }

    public static void messageClassDebug6(){
        System.debug('Thhis is the first debug class6666');
    }

    public static void messageClassDebug7(){
        System.debug('Thhis is the first debug class7777');
    }

    public static void messageClassDebug8(){
        System.debug('Thhis is the first debug class8888');
    }

    public static void messageClassDebug9(){
        System.debug('Thhis is the first debug class9999');
    }

    public static void messageClassDebug17(){
        System.debug('Thhis is the first debug class9999');
    }

    public static void messageClassDebug72(){
        System.debug('Thhis is the first debug class88888');
    }

}